### ISSUE TITLE
After launching immediately falls

### ISSUE THREAD

**Issue by dganic** [taushet/monero_mining_monitor#1]
Hello, we are experiencing problems with the launch of your product:

```
Distributor ID: Ubuntu
Description: Ubuntu 16.04.2 LTS
Release: 16.04
Codename: xenial
Python Version: 2.7.11-1
Installed using PIP:
Pandas-0.19.2
Numpy-1.12.1
```
xmr-proxy is located in the following directory:
```
/opt/xmr-proxy
```
monero_mining_monitor is located in the following directory:
```
/opt/xmr-proxy/monero_mining_monitor
```
Configuration file xmr-proxy:
```
# Ports for your workers
STRATUM_HOST = "0.0.0.0"
STRATUM_PORT = 9999

# Coin address where money goes. If you mine direct to the exchange, you MUST specify payment_id together with wallet of exchange.
WALLET = '47sghz'
# Only if you mine direct to the exchange
PAYMENT_ID = '51b81e07'

# It's useful for individually monitoring and statistic.
# In your workers you have to use any number as username (without wallet!)
ENABLE_WORKER_ID = True
WORKER_ID_FROM_IP = False

# On DwarfPool you have option to monitor your workers via email.
# If WORKER_ID is enabled, you can monitor every worker/rig separately.
MONITORING = True
MONITORING_EMAIL = 'maimail@gmail.com'

# Main pool
POOL_HOST = 'xmr-eu.dwarfpool.com'
POOL_PORT = 8050

# Failover pool
POOL_FAILOVER_ENABLE = True
POOL_HOST_FAILOVER = 'xmr-usa.dwarfpool.com'
POOL_PORT_FAILOVER = 8050

# ERROR, INFO, DEBUG
LOGLEVEL = 'INFO'
DEBUG = False
LOGFILE = "logfile.log"
```
Configuration file monero_mining_monitor:
```
#CONFIG
TIME_SHORT = '1D'                                                                               
SHORT_STEP = '20min'                                                                     
LONG_STEP = '2H'                                                                              
REPEAT = 601                                                                                    
LOG_FILE_PATH = "../log/logfile.log"    
INIT_WEB_SERVER = True                                                                
PORT = 8888  
```
When I run, I get the following error:
```
user@ubuntu-main:/opt/xmr-proxy/monero_mining_monitor$ /usr/bin/python /opt/xmr-proxy/monero_mining_monitor/mmm_code.py
----------------------------------------------------------------------------------------
--- Monero Mining Monitor 0.1
--- by u/taushet
---
--- Monitoring suite for xmr-proxy by Atredies (https://github.com/Atrides/xmr-proxy)
--- (this won't work without it!)
-----------------------------------------------------------------------------------------
Web server active on http://127.0.0.1:8888/mmm_web.html
Updating... 2017-04-17 17:31:55
Traceback (most recent call last):
  File "/opt/xmr-proxy/monero_mining_monitor/mmm_code.py", line 222, in <module>
    increment()
  File "/opt/xmr-proxy/monero_mining_monitor/mmm_code.py", line 183, in increment
    a = totalCount(df, dfTimeAll, total_file, total_html)
  File "/opt/xmr-proxy/monero_mining_monitor/mmm_code.py", line 43, in totalCount
    uptime[['A']] = uptime[['A']].astype(int)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 3054, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 3189, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 3056, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 461, in astype
    values=values, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 504, in _astype
    values = _astype_nansafe(values.ravel(), dtype, copy=True)
  File "/usr/local/lib/python2.7/dist-packages/pandas/types/cast.py", line 531, in _astype_nansafe
    raise ValueError('Cannot convert NA to integer')
ValueError: Cannot convert NA to integer
```
How to defeat her?

**Comment by hoyanf** [comment]
Error when trying to run on python3 :- 

> user@ubuntu:/opt/xmrproxy-monitor$ python3 mmm_code.py
  File "mmm_code.py", line 98
    print "Updating... "+datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                       ^
SyntaxError: invalid syntax

When trying to run on python2.7 , error is same as encountered by @dganic

**Comment by javietanh** [comment]
I found the fix:
- Install correct the version of these packages:
+ https://pypi.python.org/pypi/pandas/0.19.0/#downloads
+ http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy

Download these packages and using pip to install as follow: 
cd "download location"
pip install NAME_OF_PACKAGE

- Fixing the error:
1. Open mmm_config.py and change the log file to correct the log file of xmr-proxy (without the correct log file it can not work)
2. Open mmm_code.py: 
- line 44: uptime[['A']] = uptime[['A']].astype(int) to uptime[['A']] = uptime[['A']].astype(float) 
- line 55: dfTotal['Rejected'] = dfTotal['Shares'] - dfTotal['Accepted'] to dfTotal['Rejected'] = dfTotal['Shares'] - dfTotal['Accepted'].astype(datetime)	
- line 56: dfTotal['Elapsed'] = datetime.now() - dfTotal['Last'] to dfTotal['Elapsed'] = datetime.now() - dfTotal['Last'].astype(datetime)

Now it work...
